version: '3'

services:

  broker-service:
    build:
      context: ./broker
      dockerfile: ./broker.dockerfile
    restart: always
    ports:
      - "9090:9999"
    deploy:
      mode: replicated
      replicas: 1